export const CONTENT_MODERATION_PERMISSIONS = {
  POST_MODERATE: "POST_MODERATE",
  POST_RESTORE: "POST_RESTORE",
  POST_MODERATION_READ: "POST_MODERATION_READ",
  COMMENT_MODERATE: "COMMENT_MODERATE",
  COMMENT_RESTORE: "COMMENT_RESTORE",
  SHOP_SUSPEND: "SHOP_SUSPEND",
  SHOP_CLOSE: "SHOP_CLOSE",
  SHOP_RESTORE: "SHOP_RESTORE",
  PRODUCT_REMOVE: "PRODUCT_REMOVE",
  PRODUCT_RESTORE: "PRODUCT_RESTORE",
  PRODUCT_MODERATION_READ: "PRODUCT_MODERATION_READ",
  REVIEW_HIDE: "REVIEW_HIDE",
  REVIEW_REMOVE: "REVIEW_REMOVE",
  REVIEW_RESTORE: "REVIEW_RESTORE",
};

export function hasContentModerationPermission(permissions, code) {
  return Array.isArray(permissions) && permissions.includes(code);
}