-- Phase 4-5: payout queue + platform finance audit action types

ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'PAYOUT_SUPPORT_VIEW';
ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'PAYOUT_REQUEST_APPROVE';
ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'PAYOUT_REQUEST_REJECT';
ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'PAYOUT_REQUEST_MARK_PAID';
ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'FINANCE_SUPPORT_VIEW';
ALTER TYPE admin_action_type ADD VALUE IF NOT EXISTS 'FINANCE_SELLER_DRILL_DOWN_VIEW';
