# Applies ngrok gateway HTTPS URL to backend .env.docker.local (CORS, MinIO, PayOS) and frontend/.env.local.
# Hybrid Vite dev: localhost FE + API via ngrok (see -LocalFrontendOrigin).
# Does NOT mutate database URLs — use read-time rewrite in services instead.
#
# Usage (from Infrastructure/):
#   ./scripts/apply-ngrok-gateway-env.ps1
#   ./scripts/apply-ngrok-gateway-env.ps1 -GatewayUrl "https://your-host.ngrok-free.app"
#   ./scripts/apply-ngrok-gateway-env.ps1 -LocalFrontendOrigin "http://localhost:5174"

param(
    [string]$GatewayUrl = "",
    [string]$LocalFrontendOrigin = "http://localhost:5174"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$RepoRoot = Split-Path -Parent $Root

function Get-GatewayFromNgrokApi {
    $NgrokApi = "http://127.0.0.1:4040/api/tunnels"
    try {
        $response = Invoke-RestMethod -Uri $NgrokApi -Method Get
    } catch {
        Write-Host "Cannot reach ngrok API at $NgrokApi" -ForegroundColor Red
        Write-Host "Pass -GatewayUrl explicitly or start ngrok profile first."
        exit 1
    }
    $tunnel = $response.tunnels | Where-Object { $_.public_url -like "https://*" } | Select-Object -First 1
    if (-not $tunnel) {
        Write-Host "No HTTPS tunnel found." -ForegroundColor Red
        exit 1
    }
    return $tunnel.public_url.TrimEnd("/")
}

function Set-EnvLine {
    param(
        [string]$FilePath,
        [string]$Key,
        [string]$Value
    )
    if (-not (Test-Path $FilePath)) {
        Write-Host "Skip missing file: $FilePath" -ForegroundColor Yellow
        return
    }
    $lines = Get-Content -Path $FilePath -Encoding UTF8
    $pattern = "^\s*$([regex]::Escape($Key))\s*="
    $newLine = "$Key=$Value"
    $found = $false
    $updated = foreach ($line in $lines) {
        if ($line -match $pattern) {
            if (-not $found) {
                $found = $true
                $newLine
            }
            # Drop duplicate keys — keep first replacement only
        } else {
            $line
        }
    }
    if (-not $found) {
        $updated = $updated + $newLine
    }
    [System.IO.File]::WriteAllText($FilePath, ($updated -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
}

function Write-FrontendEnvLocal {
    param(
        [string]$Gateway,
        [string]$FilePath
    )
    $content = @"
# Auto-generated by Infrastructure/scripts/apply-ngrok-gateway-env.ps1 - do not commit.
# Hybrid: Vite on localhost, APIs via ngrok gateway. Restart npm run dev after changes.

VITE_AUTH_SERVICE_BASE_URL=$Gateway
VITE_SOCIAL_SERVICE_BASE_URL=$Gateway
VITE_COMMERCE_SERVICE_BASE_URL=$Gateway
VITE_ADMIN_SERVICE_BASE_URL=$Gateway
VITE_NOTIFICATION_SERVICE_BASE_URL=$Gateway
VITE_USE_MOCK=false
"@
    [System.IO.File]::WriteAllText($FilePath, $content.TrimEnd() + "`n", [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $FilePath" -ForegroundColor Green
}

if ([string]::IsNullOrWhiteSpace($GatewayUrl)) {
    $GatewayUrl = Get-GatewayFromNgrokApi
}

$gateway = $GatewayUrl.TrimEnd("/")
$localOrigin = $LocalFrontendOrigin.TrimEnd("/")
$localCors = "$gateway,http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174"

Write-Host "Applying gateway env: $gateway" -ForegroundColor Cyan
Write-Host "Local Vite origin (OAuth redirects): $localOrigin" -ForegroundColor Cyan

$authDockerEnv = Join-Path $RepoRoot "Services\auth-service\.env.docker.local"
$authHostEnv = Join-Path $RepoRoot "Services\auth-service\.env"
$socialEnv = Join-Path $RepoRoot "Services\social-service\.env.docker.local"
$commerceEnv = Join-Path $RepoRoot "Services\commerce-service\.env.docker.local"
$adminEnv = Join-Path $RepoRoot "Services\admin-service\.env.docker.local"
$notificationEnv = Join-Path $RepoRoot "Services\notification-service\.env.docker.local"
$frontendEnvLocal = Join-Path $RepoRoot "frontend\.env.local"

foreach ($authEnv in @($authDockerEnv, $authHostEnv)) {
    Set-EnvLine $authEnv "CORS_ALLOWED_ORIGINS" $localCors
    Set-EnvLine $authEnv "AUTH_OAUTH2_SUCCESS_REDIRECT_URL" "$localOrigin/oauth/success"
    Set-EnvLine $authEnv "AUTH_OAUTH2_FAILURE_REDIRECT_URL" "$localOrigin/oauth/failure"
    Set-EnvLine $authEnv "AUTH_OAUTH2_COOKIE_SECURE" "false"
    Set-EnvLine $authEnv "AUTH_MINIO_PRESIGNED_ENDPOINT" $gateway
    Set-EnvLine $authEnv "AUTH_MINIO_PUBLIC_URL" "$gateway/2hands-avatar"
    Set-EnvLine $authEnv "SERVER_FORWARD_HEADERS_STRATEGY" "framework"
}

Set-EnvLine $socialEnv "CORS_ALLOWED_ORIGINS" $localCors
Set-EnvLine $socialEnv "SOCIAL_MINIO_PRESIGNED_ENDPOINT" $gateway
Set-EnvLine $socialEnv "SOCIAL_MINIO_PUBLIC_URL" "$gateway/2hands-social-post"

Set-EnvLine $commerceEnv "CORS_ALLOWED_ORIGINS" $localCors
Set-EnvLine $commerceEnv "COMMERCE_MINIO_PRESIGNED_ENDPOINT" $gateway
Set-EnvLine $commerceEnv "COMMERCE_MINIO_PUBLIC_URL" $gateway
Set-EnvLine $commerceEnv "COMMERCE_PAYOS_RETURN_URL" "$gateway/commerce/checkout/payment-result"
Set-EnvLine $commerceEnv "COMMERCE_PAYOS_CANCEL_URL" "$gateway/commerce/checkout/payment-result"

Set-EnvLine $adminEnv "CORS_ALLOWED_ORIGINS" $localCors
Set-EnvLine $notificationEnv "CORS_ALLOWED_ORIGINS" $localCors

Write-FrontendEnvLocal -Gateway $gateway -FilePath $frontendEnvLocal

Write-Host ""
Write-Host "Updated auth/social/commerce/admin/notification env and frontend/.env.local." -ForegroundColor Green
Write-Host "Facebook OAuth redirect URI (Meta): $gateway/login/oauth2/code/facebook"
Write-Host "Google OAuth redirect URI: $gateway/login/oauth2/code/google"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Restart all backends:"
Write-Host "     docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.ngrok.yml --profile dev --profile ngrok restart auth-service social-service commerce-service admin-service notification-service"
Write-Host "  2. Restart frontend: npm run dev (loads frontend/.env.local)"
Write-Host "  3. Open $localOrigin (Vite may use 5174 if 5173 is busy)"
Write-Host "  4. Meta/Google OAuth: add redirect URI above; FE callback uses $localOrigin/oauth/success"
