package com.twohands.admin_service.infrastructure.persistence.jpa.enums;

public enum AdminActionType {
	USER_SUSPEND,
	PRODUCT_REMOVE,
	REVIEW_HIDE,
	REFUND_EXECUTE,
	USER_BAN,
	USER_RESTRICT,
	USER_ENFORCEMENT_REVOKE,
	SHOP_SUSPEND,
	SHOP_CLOSE,
	POST_MODERATE,
	COMMENT_MODERATE,
	SYSTEM_CONFIG_CREATE,
	SYSTEM_CONFIG_UPDATE,
	SYSTEM_CONFIG_TOGGLE,
	SYSTEM_ANNOUNCEMENT_PUBLISH,
	ORDER_SUPPORT_VIEW,
	PAYMENT_SUPPORT_VIEW,
	SHIPMENT_SUPPORT_VIEW,
	ADMIN_ACCESS_DENIED
}
