services:

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-social:
    image: postgres:16
    container_name: postgres-social

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: social_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_social_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongodb

    environment:
      MONGO_INITDB_DATABASE: social_db

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis

    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    volumes:
      - minio_data:/data

    command: server /data --console-address ":9001"

volumes:
  postgres_auth_data:
  postgres_social_data:
  mongo_data:
  minio_data: