export const NOTIFICATION_LIST_TABS = {
  ALL: "all",
  UNREAD: "unread",
};

export const NOTIFICATION_POLL_INTERVAL_MS = 60_000;

/** Auto-dismiss duration for new-notification toasts (Phase 3). */
export const NOTIFICATION_TOAST_AUTO_DISMISS_MS = 5_000;

export const NOTIFICATION_NO_DEEP_LINK_MESSAGE =
  "Thông báo này không có liên kết chi tiết.";

/**
 * Group order for notification settings UI.
 * Event types must stay in sync with notification-service NotificationDefaultChannelPolicy.
 */
export const NOTIFICATION_EVENT_GROUPS = [
  {
    id: "social",
    label: "Mạng xã hội",
    eventTypes: [
      "POST_CREATED",
      "POST_LIKED",
      "USER_FOLLOWED",
      "USER_AVATAR_UPDATED",
      "COMMENT_CREATED",
      "COMMENT_REPLIED",
      "COMMENT_LIKED",
    ],
  },
  {
    id: "commerce",
    label: "Mua sắm",
    eventTypes: [
      "ORDER_CREATED",
      "PAYMENT_SUCCESS",
      "PAYMENT_FAILED",
      "PAYMENT_REFUNDED",
      "ORDER_CANCELLED",
      "ORDER_CANCEL_PENDING_REFUND",
      "SHIPMENT_CREATED",
      "SHIPMENT_READY_TO_SHIP",
      "SHIPMENT_CANCELLED",
      "SHIPMENT_SHIPPED",
      "SHIPMENT_DELIVERED",
      "ORDER_COMPLETED",
      "PAYOUT_REQUEST_APPROVED",
      "REVIEW_REMINDER",
      "REVIEW_REPLIED",
    ],
  },
  {
    id: "account",
    label: "Tài khoản & bảo mật",
    eventTypes: [
      "USER_CREATED",
      "EMAIL_VERIFICATION_REQUESTED",
      "PASSWORD_RESET_REQUESTED",
      "PASSWORD_CHANGED",
      "USER_SUSPENDED",
      "USER_BANNED",
      "USER_RESTRICTED",
      "USER_ENFORCEMENT_REVOKED",
      "USER_ENFORCEMENT_EXPIRED",
    ],
  },
  {
    id: "seller",
    label: "Người bán",
    eventTypes: [
      "POST_MODERATED",
      "COMMENT_MODERATED",
      "COMMENT_RESTORED",
      "PRODUCT_REMOVED",
      "PRODUCT_RESTORED",
      "REVIEW_HIDDEN",
      "REVIEW_REMOVED",
      "REVIEW_RESTORED",
      "SHOP_SUSPENDED",
      "SHOP_CLOSED",
      "SHOP_RESTORED",
    ],
  },
  {
    id: "system",
    label: "Hệ thống",
    eventTypes: ["SYSTEM_ANNOUNCEMENT_SENT", "SYSTEM_ANNOUNCEMENT_CANCELLED"],
  },
];

/** Vietnamese labels for settings UI and notification type badges. */
export const NOTIFICATION_EVENT_LABELS = {
  USER_CREATED: "Tài khoản được tạo",
  EMAIL_VERIFICATION_REQUESTED: "Xác minh email",
  PASSWORD_RESET_REQUESTED: "Đặt lại mật khẩu",
  PASSWORD_CHANGED: "Đổi mật khẩu",
  POST_CREATED: "Bài viết mới",
  POST_LIKED: "Thích bài viết",
  USER_FOLLOWED: "Theo dõi",
  USER_AVATAR_UPDATED: "Cập nhật ảnh đại diện",
  COMMENT_CREATED: "Bình luận mới",
  COMMENT_REPLIED: "Trả lời bình luận",
  COMMENT_LIKED: "Thích bình luận",
  ORDER_CREATED: "Đơn hàng mới",
  PAYMENT_SUCCESS: "Thanh toán thành công",
  PAYMENT_FAILED: "Thanh toán thất bại",
  PAYMENT_REFUNDED: "Hoàn tiền thành công",
  ORDER_CANCELLED: "Đơn hàng đã hủy",
  ORDER_CANCEL_PENDING_REFUND: "Chờ hoàn tiền",
  SHIPMENT_CREATED: "Tạo vận đơn",
  SHIPMENT_READY_TO_SHIP: "Đơn sẵn sàng giao",
  SHIPMENT_CANCELLED: "Vận đơn đã hủy",
  SHIPMENT_SHIPPED: "Đơn đang giao",
  SHIPMENT_DELIVERED: "Giao hàng thành công",
  ORDER_COMPLETED: "Hoàn tất đơn hàng",
  PAYOUT_REQUEST_APPROVED: "Rút tiền được duyệt",
  REVIEW_REMINDER: "Nhắc đánh giá",
  REVIEW_REPLIED: "Shop phản hồi đánh giá",
  USER_SUSPENDED: "Tài khoản bị đình chỉ",
  USER_BANNED: "Tài khoản bị cấm",
  USER_RESTRICTED: "Tài khoản bị hạn chế",
  POST_MODERATED: "Bài viết bị kiểm duyệt",
  COMMENT_MODERATED: "Bình luận bị kiểm duyệt",
  COMMENT_RESTORED: "Bình luận được khôi phục",
  PRODUCT_REMOVED: "Sản phẩm bị gỡ",
  PRODUCT_RESTORED: "Sản phẩm được khôi phục",
  REVIEW_HIDDEN: "Đánh giá bị ẩn",
  REVIEW_REMOVED: "Đánh giá bị gỡ",
  REVIEW_RESTORED: "Đánh giá được khôi phục",
  SHOP_SUSPENDED: "Cửa hàng bị đình chỉ",
  SHOP_CLOSED: "Cửa hàng đóng",
  SHOP_RESTORED: "Cửa hàng mở lại",
  SYSTEM_ANNOUNCEMENT_SENT: "Thông báo hệ thống",
  SYSTEM_ANNOUNCEMENT_CANCELLED: "Hủy thông báo hệ thống",
  USER_ENFORCEMENT_REVOKED: "Gỡ hạn chế tài khoản",
  USER_ENFORCEMENT_EXPIRED: "Hết hạn hạn chế",
};

/** Material Symbols icon names for notification list items. */
export const NOTIFICATION_EVENT_ICONS = {
  USER_CREATED: "person_add",
  EMAIL_VERIFICATION_REQUESTED: "mark_email_read",
  PASSWORD_RESET_REQUESTED: "lock_reset",
  PASSWORD_CHANGED: "lock",
  POST_CREATED: "article",
  POST_LIKED: "favorite",
  USER_FOLLOWED: "person_add",
  USER_AVATAR_UPDATED: "account_circle",
  COMMENT_CREATED: "chat_bubble",
  COMMENT_REPLIED: "reply",
  COMMENT_LIKED: "thumb_up",
  ORDER_CREATED: "shopping_bag",
  PAYMENT_SUCCESS: "payments",
  PAYMENT_FAILED: "error",
  PAYMENT_REFUNDED: "currency_exchange",
  ORDER_CANCELLED: "cancel_presentation",
  ORDER_CANCEL_PENDING_REFUND: "hourglass_top",
  SHIPMENT_CREATED: "local_shipping",
  SHIPMENT_READY_TO_SHIP: "inventory_2",
  SHIPMENT_CANCELLED: "cancel",
  SHIPMENT_SHIPPED: "local_shipping",
  SHIPMENT_DELIVERED: "package_2",
  ORDER_COMPLETED: "check_circle",
  PAYOUT_REQUEST_APPROVED: "account_balance_wallet",
  REVIEW_REMINDER: "rate_review",
  REVIEW_REPLIED: "forum",
  USER_SUSPENDED: "gavel",
  USER_BANNED: "block",
  USER_RESTRICTED: "shield",
  POST_MODERATED: "policy",
  COMMENT_MODERATED: "policy",
  COMMENT_RESTORED: "restore",
  PRODUCT_REMOVED: "inventory",
  PRODUCT_RESTORED: "inventory_2",
  REVIEW_HIDDEN: "visibility_off",
  REVIEW_REMOVED: "rate_review",
  REVIEW_RESTORED: "restore",
  SHOP_SUSPENDED: "store",
  SHOP_CLOSED: "storefront",
  SHOP_RESTORED: "store",
  SYSTEM_ANNOUNCEMENT_SENT: "campaign",
  SYSTEM_ANNOUNCEMENT_CANCELLED: "campaign",
  USER_ENFORCEMENT_REVOKED: "verified_user",
  USER_ENFORCEMENT_EXPIRED: "timer_off",
};

export const ANNOUNCEMENT_SEVERITY_STYLES = {
  INFO: "border-primary/30 bg-primary/5 text-on-surface",
  WARNING: "border-amber-400/50 bg-amber-50 text-on-surface",
  CRITICAL: "border-error/40 bg-error-container text-on-error-container",
};
