export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
};

export const PAYOS_AUTO_REDIRECT_MS = 2000;

export const PAYMENT_STATUS_POLL_INTERVAL_MS = 5000;

export const PAYMENT_STATUS_POLL_MAX_ATTEMPTS = 6;
