export const APP_ROUTES = {
  home: "/",
  login: "/auth/login",
  register: "/auth/register",
  forgotPassword: "/auth/forgot-password",
  verifyEmail: "/auth/verify-email",
  oauthSuccess: "/oauth/success",
  oauthFailure: "/oauth/failure",
  account: "/account-profile",
  accountSecurity: "/account/security",
  accountPassword: "/account/password",
  changePassword: "/account/change-password",
  sessionExpired: "/auth/session-expired",
  admin: "/admin",
  socialFeed: "/social",
  socialSavedPosts: "/social/saved",
  socialSearchPosts: "/social/search",
  socialHashtagPosts: "/social/tags/:hashtag",
  socialProfile: "/social/users/:userId",
  commerceHome: "/commerce",
  commerceSearch: "/commerce/search",
  commerceCategoryProducts: "/commerce/categories/:categoryId",
  commerceShopProducts: "/commerce/shops/:shopId",
  commerceProductDetail: "/commerce/products/:productId",
  commerceCart: "/commerce/cart",
};

